- README.md
> [enhanceDocu] Add precondition to docu

- README.md
@scherler some docs re the issue I hit this morning
> troubleshooting docs in readme

- src/test/js/karaoke-freestyle.js
add more time to do the comparison
> [karaokeMoreWait] adding more wait to detect current broken master

- src/test/js/karaoke-freestyle.js
- src/test/js/karaoke-noStages.js
- src/test/js/karaoke-stages.js
- src/test/js/test_pipelines_scripts/stages-with-wait.groovy
> Karaoke more wait

- README.md
- logging.properties
- package.json
- run.sh
- src/main/js/api/debug.js
- src/main/js/api/sse.js
- src/main/js/custom_commands/waitForJobRunEnded.js
- src/main/js/custom_commands/waitForJobRunStarted.js
- src/main/js/globals.js
See [JENKINS-36763](https://issues.jenkins-ci.org/browse/JENKINS-36763) and [JENKINS-36704](https://issues.jenkins-ci.org/browse/JENKINS-36704).
Depends on https://github.com/jenkinsci/blueocean-plugin/pull/356
@jenkinsci/code-reviewers @reviewbybees (esp @scherler)
> [FIX JENKINS-36763 and JENKINS-36704] SSE client connection handling + better logging

- src/main/js/api/sse.js
- src/main/js/page_objects/classic_jenkins/freestyleCreate.js
- src/main/js/page_objects/classic_jenkins/pipelineCreate.js
@jenkinsci/code-reviewers @reviewbybees esp @scherler
> Wait for job created event before trying to navigate to the config page

- src/main/js/api/sse.js
- src/main/js/custom_commands/waitForJobCreated.js
- src/main/js/custom_commands/waitForJobDeleted.js
- src/main/js/custom_commands/waitForJobRunStarted.js
- src/main/js/page_objects/classic_jenkins/freestyleCreate.js
- src/main/js/page_objects/classic_jenkins/pipeline.js
- src/main/js/page_objects/classic_jenkins/pipelineCreate.js
@scherler more tweaks ... this time to make sure the build does not hang waiting on a run to start. There are still some strange things happening.
What I don't get yet is why the hell `karaoke-noStages.js` seems to move through the test without waiting for browser.end() etc. I wonder if it's a Selenium server version issue in the Docker image used for testing?
> Wait tweaks

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/noStages.js
- src/test/resources/test_scripts/no-stages.groovy
Uses changes in https://github.com/jenkinsci/blueocean-plugin/pull/391 that will hopefully make the test flow in a more predictable way and therefore less prone to flaky failures.
> attempt to harden test log-karaoke/noStages.js

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/stages.js
- src/test/resources/test_scripts/stages-with-wait.groovy
See [JENKINS-37640](https://issues.jenkins-ci.org/browse/JENKINS-37640).
Add test for artifacts tab not being empty. Add snippet for artifact generation 
> [JENKINS-37640] Add test for artifacts tab to not be empty

- README.md
- package.json
- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/stages.js
update npm deps to the newest versions
> [updateNpmModules] Update all deps

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/queued.js
See [JENKINS-37954](https://issues.jenkins-ci.org/browse/JENKINS-37954).
> [FIX JENKINS-37954] better selector for the queued empty state

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/edgeCases/folder.js
- src/test/js/failing.js
- src/test/js/log-karaoke/freestyle.js
- src/test/js/log-karaoke/freestylePing.js
- src/test/js/log-karaoke/noStages.js
- src/test/js/log-karaoke/stages.js
- src/test/resources/test_scripts/freestylePing.sh
See [JENKINS-38006](https://issues.jenkins-ci.org/browse/JENKINS-38006).
> FIX Jenkins 38006 Fix condition which had been implemented wrong

- src/main/js/page_objects/blueocean/bluePipelineActivity.js
- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/stages.js
- src/test/resources/test_scripts/stages-with-wait-block-syntax.groovy
- src/test/resources/test_scripts/stages-with-wait-pipelineModel-syntax.groovy
- src/test/resources/test_scripts/stages-with-wait.groovy
In addtion to https://github.com/jenkinsci/blueocean-plugin/pull/467 creating test based on new syntax
> [FIX JENKINS-38017 JENKINS-37323] Implement test cases with new syntax

- Dockerfile
- src/main/js/api/git.js
> Fix linux dep

- src/main/js/page_objects/classic_jenkins/multibranchCreate.js
- src/main/js/util/url.js
> [hotfix/suffix] fix create url of multibranch

- src/main/js/page_objects/blueocean/bluePipelineActivity.js
- src/test/js/smoke.js
See [JENKINS-36615](https://issues.jenkins-ci.org/browse/JENKINS-36615).
AT for https://github.com/jenkinsci/blueocean-plugin/pull/501
Add test for clicking on run button then on the emerging toast the open
@jenkinsci/code-reviewers @reviewbybees 
…ing toast the open
> [FIX JENKINS-36615] REGRESSION open link on toast is not working

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/noStages.js
- src/test/js/log-karaoke/parallelStages.js
- src/test/resources/test_scripts/parallel-stages.groovy
REGRESSION-TEST: parallel karaoke not allowing branch selection or completing correctly
See [JENKINS-37962](https://issues.jenkins-ci.org/browse/JENKINS-37962).
AT for https://github.com/jenkinsci/blueocean-plugin/pull/499
> FIX Jenkins-37962 REGRESSION: parallel karaoke not allowing branch selection or completing correctly

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/parallelStages.js
- src/test/resources/test_scripts/parallel-stages.groovy
See [JENKINS-37753](https://issues.jenkins-ci.org/browse/JENKINS-37753).
AT for https://github.com/jenkinsci/blueocean-plugin/pull/520
@jenkinsci/code-reviewers @reviewbybees 
…ith the update center mirror
> [JENKINS-37753] REGRESSION: Steps showing up as incomplete when they are in fact complete

- Jenkinsfile
> Send hipchat message for ATH

- Jenkinsfile
More pipeline pain ... paramaterised builds fail on first run if you don't do something like this.
> Handle first run of the pipeline when no build parameter is set

- Jenkinsfile
See [JENKINS-37918](https://issues.jenkins-ci.org/browse/JENKINS-37918).
Misc tweaks trying to fix issues identified on the master branch.
https://ci.blueocean.io/job/ATH-Jenkinsfile/job/Jenkinsfile-tweaks/
@jenkinsci/code-reviewers @reviewbybees 
- deleteDir at the start of the build
- remove sh to delete the blueocean-plugin dir as it was failing for some reason
- Better message for when build aborted due to uninitialised build params
- Support for etting plugins from the "latest" build on a branch
> A few jenkinsfile tweaks

- Jenkinsfile
Allow people to specify an optional repo so they can build forks. 
Also says branch name in hipchat message
@reviewbybees @tfennelly
> Allow building of forks

- Jenkinsfile
- src/main/js/custom_commands/moveClassicBottomStickyButtons.js
- src/main/js/globals.js
- src/main/js/page_objects/classic_jenkins/folderCreate.js
- src/main/js/page_objects/classic_jenkins/freestyleConfig.js
- src/main/js/page_objects/classic_jenkins/freestyleCreate.js
- src/main/js/page_objects/classic_jenkins/multibranchCreate.js
- src/main/js/page_objects/classic_jenkins/pipelineConfig.js
- src/main/js/page_objects/classic_jenkins/pipelineCreate.js
- src/test/js/smoke.js
See [JENKINS-37918](https://issues.jenkins-ci.org/browse/JENKINS-37918).
> Remove sticky class buttons completely

- Jenkinsfile
See [JENKINS-37918](https://issues.jenkins-ci.org/browse/JENKINS-37918).
> Default run against latest master

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
See [JENKINS-37925](https://issues.jenkins-ci.org/browse/JENKINS-37925).
> [JENKINS-37925] change full log link in steps to the backend log

- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/freestyle.js
- src/test/resources/test_scripts/freestyle.sh
See [JENKINS-38673](https://issues.jenkins-ci.org/browse/JENKINS-38673).
> [JENKINS-38673] update tests to run more stable

- src/main/js/custom_commands/moveClassicBottomStickyButtons.js
- src/main/js/custom_commands/removePageHead.js
- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/log-karaoke/stages.js
- src/test/resources/test_scripts/stages-with-wait-block-syntax.groovy
- src/test/resources/test_scripts/stages-with-wait-pipelineModel-syntax.groovy
- src/test/resources/test_scripts/stages-with-wait.groovy
See [JENKINS-38248](https://issues.jenkins-ci.org/browse/JENKINS-38248).
> FIX Jenkins 38248

- Jenkinsfile
Like jenkinsci/blueocean-plugin#554. Take advantage of the Maven proxy to speed things up a bit.
> Use the Maven global configuration to speed up builds a bit

- package.json
- src/main/js/api/sse.js
- src/main/js/globals.js
See [JENKINS-37206](https://issues.jenkins-ci.org/browse/JENKINS-37206). A hopefully more stable SSE client + local tweaks to help stability.
> [FIX JENKINS-37206] Updated to use newer SSE client for stability

- Jenkinsfile
My bad, I missed the fact that Maven was started in a sub folder
> Fix Maven settings.xml location

- src/main/js/page_objects/classic_jenkins/multibranchCreate.js
- src/test/js/multibranch/noRunsActivityPage.js
Checks that multibranch job with no branches shows activities correctly.
See [JENKINS-39981](https://issues.jenkins-ci.org/browse/JENKINS-39981).
> [JENKINS-39981] Check no activities in multibranch job renders properly

- src/test/js/notMultibranch/freestyleRunning.js
- src/test/js/notMultibranch/index.js
- src/test/js/notMultibranch/pipelineRunning.js
Wanted to excercise non multibranch run button. Freestyle and pipeline. 
Checks that it runs, shows up in list, toast, finishes etc. 
> Test running from activity screen non multibranch

- src/test/js/multibranch/multibranchOpening.js
- src/test/resources/multibranch_2/Jenkinsfile
https://issues.jenkins-ci.org/browse/JENKINS-40027 is bad. 
This checks it won't be bad. 
cc @scherler @imeredith @tfennelly
> test to cover JENKINS-40027

- Jenkinsfile
> Remove stacktrace from hipchat notifications

- src/main/js/page_objects/blueocean/bluePipelineActivity.js
- src/test/js/multibranch/multibranchOpening.js
> Refactor out common stage graph assertion and doc

- src/test/resources/test_scripts/stages-with-wait-block-syntax.groovy
- src/test/resources/test_scripts/stages-with-wait-pipelineModel-syntax.groovy
- src/test/resources/test_scripts/stages-with-wait.groovy
> relax the timing a bit as often jobs are finished

- src/test/js/artifacts/artifacts.js
- src/test/resources/test_scripts/lots-of-artifacts.groovy
See [JENKINS-39761](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
@reviewbybees
> [JENKINS-39761 Adds tests to cover the artifacts tab on run details.

- src/main/js/api/git.js
- src/test/js/multibranch/commitMessages.js
- src/test/resources/multibranch/commit_message/Jenkinsfile
See [JENKINS-40296](https://issues.jenkins-ci.org/browse/JENKINS-40296).
BO PR https://github.com/jenkinsci/blueocean-plugin/pull/651
@reviewbybees
> [JENKINS-40296] Tests to cover changeset messages

- src/test/js/artifacts/artifacts.js
- src/test/js/notMultibranch/pipelineRunning.js
It make more sense to click on the run button than use classic (as we are testing blue ocean here).
> don't test classic, test blue ocean run button

- src/test/js/notMultibranch/freestyleRunning.js
See [JENKINS-40854](https://issues.jenkins-ci.org/browse/JENKINS-40854).
@reviewbybees
> [JENKINS-40854] Check to make sure that run button is showing correctly

- src/main/js/page_objects/classic_jenkins/matrixCreate.js
- src/test/js/matrix.js
See [JENKINS-37427](https://issues.jenkins-ci.org/browse/JENKINS-37427).
BlueOcean PR: https://github.com/jenkinsci/blueocean-plugin/pull/708
@reviewbybees
> [JENKINS-37427] Check to make sure we are linking to classic Jenkins

- src/test/js/edgeCases/folder.js
> SCM api integration fixes

- src/test/js/edgeCases/folder.js
This reverts commit 0353ea5fdbf5587f7b6265e7043c7f38bfcc833f.
@reviewbybees
> Revert "SCM api integration fixes (#101)"

- Jenkinsfile
Better error message for when CopyArtifacts fails to get the plugins jar from the upstream BO build.
Trying to diagnose an issue @vivek and @michaelneale are having.
@reviewbybees
> Better error message for when CopyArtifacts fails

- src/test/js/multibranch/testResults.js
- src/test/resources/multibranch/test_results/TEST-io.blueocean.StdoutStderr.xml
See [JENKINS-38754](https://issues.jenkins-ci.org/browse/JENKINS-38754).
@reviewbybees
> [JENKINS-38754] Add test coverage for Standoutput and standard error

- src/main/js/custom_commands/waitForElementVisibleThenClick.js
- src/test/js/multibranch/noRunsActivityPage.js
See [JENKINS-40740](https://issues.jenkins-ci.org/browse/JENKINS-40740).
PR https://github.com/jenkinsci/blueocean-plugin/pull/741
@reviewbybees
> [JENKINS-40740] Ath tests to cover missing run data

- src/main/resources/log4j.properties
Making it easier to read the feck'n logs on the CI server
@reviewbybees
> Add a log4j.properties

- Jenkinsfile
- Archive the test reports so they are viewable in blue ocean
- Example: https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/experiment%2Fenable-junit-archiver/1/tests
@reviewbybees
> experiment with enabling test reporting

- src/main/js/custom_commands/waitForJobRunUnpaused.js
- src/main/js/page_objects/blueocean/bluePipelineActivity.js
- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/main/js/page_objects/blueocean/bluePipelines.js
- src/main/js/util/url.js
- src/test/js/artifacts/artifacts.js
- src/test/js/edgeCases/runDetailsDeepLink.js
- src/test/js/failingStages.js
- src/test/js/log-karaoke/noStages.js
- src/test/js/multibranch/multibranchOpening.js
- src/test/js/multibranch/testResults.js
- src/test/resources/test_scripts/fastStages.groovy
- src/test/resources/test_scripts/freestylePing.sh
- src/test/resources/test_scripts/initialStage.groovy
- src/test/resources/test_scripts/parallel-stages.groovy
cc @tfennelly @sophistifunk @scherler starting to change the styles to match the new header stuff. 
Smokes now passes, as does much of log-karaoke (I need to go to bed now, but will try more tomorro)
> tweaking for new headers

- src/test/js/creation/git/localRepo.js
> have to skip these

- src/main/js/page_objects/blueocean/blueMultiBranchPipeline.js
- src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- src/test/js/multibranch/folder.js
Tests for https://github.com/jenkinsci/blueocean-plugin/pull/847
See [JENKINS-38751](https://issues.jenkins-ci.org/browse/JENKINS-38751).
@reviewbybees
> exit to classic jenkins tests

- src/main/js/page_objects/blueocean/bluePipelineActivity.js
See [JENKINS-41642](https://issues.jenkins-ci.org/browse/JENKINS-41642).
@reviewbybees
> fix toast selector (wrt JENKINS-41642)

- src/test/resources/multibranch/commit_message/Jenkinsfile
Required as checkout scm is needed to see changes 
@reviewbybees
> need to have checkout scm

- .gitignore
- src/test/js/log-karaoke/noStages.js
> Jenkins 40526 log links

- src/main/js/page_objects/blueocean/bluePipelineActivity.js
- src/test/js/freestyle/branchPRTabs.js
Companion PR for @cliffmeyers PR: https://github.com/jenkinsci/blueocean-plugin/pull/929
> small changes for new non shoes style empty states

- Jenkinsfile
- Differentiating between builds that failed and those that were aborted.
@reviewbybees
> experiment / improve hipchat message

- src/main/nightwatch.json
> Remove ANSII encoding from log
